import "dotenv/config";
import { prisma } from "../src/lib/prisma";

const SERVICE_TYPES = [
  "pickup_delivery",
  "junk_removal",
  "small_moves",
  "appliance_transport",
  "furniture_transport",
  "mulch_delivery",
  "yard_waste_haul",
  "snow_plowing",
  "salt_spreading",
  "snow_haul",
  "firewood_delivery",
  "leaf_cleanup_haul",
] as const;

const VEHICLE_TYPES = ["pickup", "pickup_trailer", "flatbed", "box_truck", "dump_truck"] as const;
const AVAILABILITY_TYPES = ["always", "weekends", "after_5pm", "custom"] as const;
const MEMBERSHIP_TIERS = ["standard", "premium"] as const;

const DAILY_HOURS = {
  monday: { start: "08:00", end: "18:00" },
  tuesday: { start: "08:00", end: "18:00" },
  wednesday: { start: "08:00", end: "18:00" },
  thursday: { start: "08:00", end: "18:00" },
  friday: { start: "08:00", end: "18:00" },
  saturday: { start: "09:00", end: "14:00" },
  sunday: null,
};

const TRUCK_OWNERS = [
  {
    email: "mike@truck.local",
    name: "Mike Johnson",
    fullName: "Mike Johnson",
    phone: "555-123-4567",
    bio: "Local pickup and flatbed. Available for hauls, moves, and seasonal work. Reliable and insured.",
    serviceRadiusMiles: 25,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.8,
    totalJobsCompleted: 42,
    vehicleType: "pickup" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 2000,
    hourlyRate: 75,
    minimumJobPrice: 50,
    perMileRate: 2.5,
    availabilityType: "custom" as const,
    services: ["pickup_delivery", "junk_removal", "small_moves", "snow_plowing", "salt_spreading", "mulch_delivery", "yard_waste_haul"],
  },
  {
    email: "sarah@truck.local",
    name: "Sarah Chen",
    fullName: "Sarah Chen",
    phone: "555-234-5678",
    bio: "Professional moving and delivery. Specializing in furniture, appliances, and junk removal. 10+ years experience.",
    serviceRadiusMiles: 35,
    platformFeePct: 12,
    membershipTier: "premium" as const,
    ratingAvg: 4.9,
    totalJobsCompleted: 156,
    vehicleType: "box_truck" as const,
    bedLengthFt: 16,
    payloadCapacityLbs: 5000,
    hourlyRate: 95,
    minimumJobPrice: 75,
    perMileRate: 3,
    availabilityType: "always" as const,
    services: ["pickup_delivery", "junk_removal", "small_moves", "appliance_transport", "furniture_transport"],
  },
  {
    email: "derek@truck.local",
    name: "Derek Martinez",
    fullName: "Derek Martinez",
    phone: "555-345-6789",
    bio: "Snow removal specialist. Plowing, salting, snow haul. Available 24/7 during storms.",
    serviceRadiusMiles: 20,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.7,
    totalJobsCompleted: 89,
    vehicleType: "pickup" as const,
    bedLengthFt: 6.5,
    payloadCapacityLbs: 1800,
    hourlyRate: 85,
    minimumJobPrice: 60,
    perMileRate: 2.75,
    availabilityType: "always" as const,
    services: ["snow_plowing", "salt_spreading", "snow_haul"],
  },
  {
    email: "james@truck.local",
    name: "James Wilson",
    fullName: "James Wilson",
    phone: "555-456-7890",
    bio: "Landscape and yard work. Mulch, firewood, yard waste, leaf cleanup. Spring and fall specialist.",
    serviceRadiusMiles: 30,
    platformFeePct: 14,
    membershipTier: "standard" as const,
    ratingAvg: 4.6,
    totalJobsCompleted: 67,
    vehicleType: "dump_truck" as const,
    bedLengthFt: 12,
    payloadCapacityLbs: 8000,
    hourlyRate: 120,
    minimumJobPrice: 100,
    perMileRate: 4,
    availabilityType: "weekends" as const,
    services: ["mulch_delivery", "yard_waste_haul", "firewood_delivery", "leaf_cleanup_haul"],
  },
  {
    email: "emma@truck.local",
    name: "Emma Thompson",
    fullName: "Emma Thompson",
    phone: "555-567-8901",
    bio: "Evening and weekend availability. Great for last-minute moves and deliveries after work.",
    serviceRadiusMiles: 22,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.5,
    totalJobsCompleted: 34,
    vehicleType: "pickup_trailer" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 3500,
    hourlyRate: 70,
    minimumJobPrice: 45,
    perMileRate: 2.25,
    availabilityType: "after_5pm" as const,
    services: ["pickup_delivery", "small_moves", "furniture_transport", "appliance_transport"],
  },
  {
    email: "carlos@truck.local",
    name: "Carlos Rivera",
    fullName: "Carlos Rivera",
    phone: "555-678-9012",
    bio: "Flatbed specialist. Heavy loads, construction materials, equipment. Towing available.",
    serviceRadiusMiles: 40,
    platformFeePct: 12,
    membershipTier: "premium" as const,
    ratingAvg: 4.9,
    totalJobsCompleted: 203,
    vehicleType: "flatbed" as const,
    bedLengthFt: 20,
    payloadCapacityLbs: 10000,
    hourlyRate: 110,
    minimumJobPrice: 90,
    perMileRate: 3.5,
    availabilityType: "custom" as const,
    services: ["pickup_delivery", "appliance_transport", "furniture_transport", "junk_removal"],
  },
  {
    email: "lisa@truck.local",
    name: "Lisa Park",
    fullName: "Lisa Park",
    phone: "555-789-0123",
    bio: "Full-service junk removal and hauling. Same-day available. Eco-friendly disposal when possible.",
    serviceRadiusMiles: 28,
    platformFeePct: 14,
    membershipTier: "standard" as const,
    ratingAvg: 4.8,
    totalJobsCompleted: 112,
    vehicleType: "pickup" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 2200,
    hourlyRate: 80,
    minimumJobPrice: 55,
    perMileRate: 2.5,
    availabilityType: "always" as const,
    services: ["junk_removal", "pickup_delivery", "yard_waste_haul", "small_moves"],
  },
  {
    email: "tyrone@truck.local",
    name: "Tyrone Williams",
    fullName: "Tyrone Williams",
    phone: "555-890-1234",
    bio: "Budget-friendly hauls. Student and first-time mover friendly. Flexible scheduling.",
    serviceRadiusMiles: 18,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.4,
    totalJobsCompleted: 28,
    vehicleType: "pickup" as const,
    bedLengthFt: 6.5,
    payloadCapacityLbs: 1500,
    hourlyRate: 55,
    minimumJobPrice: 35,
    perMileRate: 1.75,
    availabilityType: "weekends" as const,
    services: ["pickup_delivery", "small_moves", "junk_removal"],
  },
  {
    email: "natalie@truck.local",
    name: "Natalie Foster",
    fullName: "Natalie Foster",
    phone: "555-901-2345",
    bio: "Premium moving experience. White-glove furniture handling. Antiques and delicate items welcome.",
    serviceRadiusMiles: 50,
    platformFeePct: 10,
    membershipTier: "premium" as const,
    ratingAvg: 5.0,
    totalJobsCompleted: 89,
    vehicleType: "box_truck" as const,
    bedLengthFt: 20,
    payloadCapacityLbs: 6000,
    hourlyRate: 135,
    minimumJobPrice: 120,
    perMileRate: 4.5,
    availabilityType: "custom" as const,
    services: ["furniture_transport", "appliance_transport", "small_moves", "pickup_delivery"],
  },
  {
    email: "kevin@truck.local",
    name: "Kevin O'Brien",
    fullName: "Kevin O'Brien",
    phone: "555-012-3456",
    bio: "All-season hauler. Winter plow, spring mulch, summer junk, fall leaves. One truck, year-round.",
    serviceRadiusMiles: 25,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.7,
    totalJobsCompleted: 78,
    vehicleType: "pickup" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 2400,
    hourlyRate: 72,
    minimumJobPrice: 48,
    perMileRate: 2.25,
    availabilityType: "custom" as const,
    services: ["pickup_delivery", "junk_removal", "mulch_delivery", "yard_waste_haul", "snow_plowing", "leaf_cleanup_haul", "firewood_delivery"],
  },
  {
    email: "marcus@truck.local",
    name: "Marcus Hayes",
    fullName: "Marcus Hayes",
    phone: "555-111-2222",
    bio: "Retired contractor. Dump truck for big yard projects. Mulch, gravel, demolition debris.",
    serviceRadiusMiles: 22,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.6,
    totalJobsCompleted: 54,
    vehicleType: "dump_truck" as const,
    bedLengthFt: 14,
    payloadCapacityLbs: 10000,
    hourlyRate: 115,
    minimumJobPrice: 95,
    perMileRate: 3.75,
    availabilityType: "weekends" as const,
    services: ["mulch_delivery", "yard_waste_haul", "junk_removal", "firewood_delivery"],
  },
  {
    email: "priya@truck.local",
    name: "Priya Sharma",
    fullName: "Priya Sharma",
    phone: "555-222-3333",
    bio: "Quick and careful. Same-day pickup and delivery. Furniture, appliances, estate cleanouts.",
    serviceRadiusMiles: 30,
    platformFeePct: 14,
    membershipTier: "standard" as const,
    ratingAvg: 4.9,
    totalJobsCompleted: 134,
    vehicleType: "box_truck" as const,
    bedLengthFt: 18,
    payloadCapacityLbs: 4500,
    hourlyRate: 88,
    minimumJobPrice: 65,
    perMileRate: 2.75,
    availabilityType: "always" as const,
    services: ["pickup_delivery", "furniture_transport", "appliance_transport", "small_moves", "junk_removal"],
  },
  {
    email: "brandon@truck.local",
    name: "Brandon Scott",
    fullName: "Brandon Scott",
    phone: "555-333-4444",
    bio: "Snow crew. Commercial and residential plowing. Salt, sand, snow removal.",
    serviceRadiusMiles: 15,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.8,
    totalJobsCompleted: 212,
    vehicleType: "pickup" as const,
    bedLengthFt: 6.5,
    payloadCapacityLbs: 1600,
    hourlyRate: 90,
    minimumJobPrice: 70,
    perMileRate: 2.5,
    availabilityType: "always" as const,
    services: ["snow_plowing", "salt_spreading", "snow_haul"],
  },
  {
    email: "olivia@truck.local",
    name: "Olivia Reed",
    fullName: "Olivia Reed",
    phone: "555-444-5555",
    bio: "Apartment moves, dorm pickups, small deliveries. No job too small.",
    serviceRadiusMiles: 20,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.5,
    totalJobsCompleted: 41,
    vehicleType: "pickup" as const,
    bedLengthFt: 6.5,
    payloadCapacityLbs: 1400,
    hourlyRate: 58,
    minimumJobPrice: 40,
    perMileRate: 1.9,
    availabilityType: "after_5pm" as const,
    services: ["pickup_delivery", "small_moves", "furniture_transport"],
  },
  {
    email: "andre@truck.local",
    name: "Andre Santos",
    fullName: "Andre Santos",
    phone: "555-555-6666",
    bio: "Construction and landscaping. Flatbed for equipment, materials, oversized loads.",
    serviceRadiusMiles: 45,
    platformFeePct: 12,
    membershipTier: "premium" as const,
    ratingAvg: 4.9,
    totalJobsCompleted: 178,
    vehicleType: "flatbed" as const,
    bedLengthFt: 22,
    payloadCapacityLbs: 12000,
    hourlyRate: 125,
    minimumJobPrice: 100,
    perMileRate: 4,
    availabilityType: "custom" as const,
    services: ["pickup_delivery", "appliance_transport", "furniture_transport", "junk_removal", "mulch_delivery"],
  },
  {
    email: "yuki@truck.local",
    name: "Yuki Tanaka",
    fullName: "Yuki Tanaka",
    phone: "555-666-7777",
    bio: "Leaf cleanup and yard waste specialist. Fall season bookings fill fast.",
    serviceRadiusMiles: 18,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.7,
    totalJobsCompleted: 92,
    vehicleType: "pickup" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 2000,
    hourlyRate: 68,
    minimumJobPrice: 45,
    perMileRate: 2,
    availabilityType: "custom" as const,
    services: ["leaf_cleanup_haul", "yard_waste_haul", "mulch_delivery"],
  },
  {
    email: "dwayne@truck.local",
    name: "Dwayne Mitchell",
    fullName: "Dwayne Mitchell",
    phone: "555-777-8888",
    bio: "Firewood delivery. Cord wood, split, seasoned. Also mulch and stone.",
    serviceRadiusMiles: 25,
    platformFeePct: 14,
    membershipTier: "standard" as const,
    ratingAvg: 4.8,
    totalJobsCompleted: 67,
    vehicleType: "dump_truck" as const,
    bedLengthFt: 10,
    payloadCapacityLbs: 6000,
    hourlyRate: 95,
    minimumJobPrice: 75,
    perMileRate: 3,
    availabilityType: "weekends" as const,
    services: ["firewood_delivery", "mulch_delivery", "yard_waste_haul"],
  },
  {
    email: "sophia@truck.local",
    name: "Sophia Nguyen",
    fullName: "Sophia Nguyen",
    phone: "555-888-9999",
    bio: "Moving day specialist. Box truck with ramp. Careful with antiques and pianos.",
    serviceRadiusMiles: 35,
    platformFeePct: 12,
    membershipTier: "premium" as const,
    ratingAvg: 5.0,
    totalJobsCompleted: 98,
    vehicleType: "box_truck" as const,
    bedLengthFt: 20,
    payloadCapacityLbs: 5500,
    hourlyRate: 105,
    minimumJobPrice: 85,
    perMileRate: 3.25,
    availabilityType: "custom" as const,
    services: ["small_moves", "furniture_transport", "appliance_transport", "pickup_delivery"],
  },
  {
    email: "jake@truck.local",
    name: "Jake Morrison",
    fullName: "Jake Morrison",
    phone: "555-999-0000",
    bio: "Weekend warrior. Pickup and trailer for hauling. Junk, yard waste, small moves.",
    serviceRadiusMiles: 20,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.4,
    totalJobsCompleted: 23,
    vehicleType: "pickup_trailer" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 3000,
    hourlyRate: 62,
    minimumJobPrice: 42,
    perMileRate: 2,
    availabilityType: "weekends" as const,
    services: ["junk_removal", "yard_waste_haul", "pickup_delivery", "small_moves"],
  },
  {
    email: "fatima@truck.local",
    name: "Fatima Hassan",
    fullName: "Fatima Hassan",
    phone: "555-100-2000",
    bio: "Estate sales, cleanouts, donation runs. Respectful and efficient.",
    serviceRadiusMiles: 28,
    platformFeePct: 14,
    membershipTier: "standard" as const,
    ratingAvg: 4.9,
    totalJobsCompleted: 76,
    vehicleType: "box_truck" as const,
    bedLengthFt: 16,
    payloadCapacityLbs: 4000,
    hourlyRate: 82,
    minimumJobPrice: 60,
    perMileRate: 2.5,
    availabilityType: "always" as const,
    services: ["junk_removal", "pickup_delivery", "furniture_transport", "small_moves"],
  },
  {
    email: "connor@truck.local",
    name: "Connor Walsh",
    fullName: "Connor Walsh",
    phone: "555-200-3000",
    bio: "Winter plow guy. Residential driveways. Fair pricing, reliable.",
    serviceRadiusMiles: 12,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.6,
    totalJobsCompleted: 145,
    vehicleType: "pickup" as const,
    bedLengthFt: 6.5,
    payloadCapacityLbs: 1700,
    hourlyRate: 78,
    minimumJobPrice: 55,
    perMileRate: 2.25,
    availabilityType: "always" as const,
    services: ["snow_plowing", "salt_spreading"],
  },
  {
    email: "isabella@truck.local",
    name: "Isabella Cruz",
    fullName: "Isabella Cruz",
    phone: "555-300-4000",
    bio: "Local delivery pro. Store runs, Craigslist pickups, marketplace hauls.",
    serviceRadiusMiles: 25,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.7,
    totalJobsCompleted: 89,
    vehicleType: "pickup" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 2100,
    hourlyRate: 65,
    minimumJobPrice: 42,
    perMileRate: 2.1,
    availabilityType: "custom" as const,
    services: ["pickup_delivery", "appliance_transport", "furniture_transport"],
  },
  {
    email: "vijay@truck.local",
    name: "Vijay Patel",
    fullName: "Vijay Patel",
    phone: "555-400-5000",
    bio: "Mulch, topsoil, gravel delivery. Landscaping supply runs. Dump truck.",
    serviceRadiusMiles: 30,
    platformFeePct: 14,
    membershipTier: "standard" as const,
    ratingAvg: 4.8,
    totalJobsCompleted: 112,
    vehicleType: "dump_truck" as const,
    bedLengthFt: 12,
    payloadCapacityLbs: 9000,
    hourlyRate: 108,
    minimumJobPrice: 88,
    perMileRate: 3.5,
    availabilityType: "custom" as const,
    services: ["mulch_delivery", "yard_waste_haul", "firewood_delivery"],
  },
  {
    email: "maya@truck.local",
    name: "Maya Johnson",
    fullName: "Maya Johnson",
    phone: "555-500-6000",
    bio: "College town specialist. Dorm moves, storage unit runs, furniture swaps.",
    serviceRadiusMiles: 15,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.5,
    totalJobsCompleted: 56,
    vehicleType: "pickup_trailer" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 3200,
    hourlyRate: 68,
    minimumJobPrice: 48,
    perMileRate: 2.2,
    availabilityType: "weekends" as const,
    services: ["small_moves", "pickup_delivery", "furniture_transport", "junk_removal"],
  },
  {
    email: "ricardo@truck.local",
    name: "Ricardo Mendez",
    fullName: "Ricardo Mendez",
    phone: "555-600-7000",
    bio: "Heavy equipment transport. Flatbed for tractors, mowers, ATVs.",
    serviceRadiusMiles: 50,
    platformFeePct: 10,
    membershipTier: "premium" as const,
    ratingAvg: 4.9,
    totalJobsCompleted: 167,
    vehicleType: "flatbed" as const,
    bedLengthFt: 24,
    payloadCapacityLbs: 14000,
    hourlyRate: 140,
    minimumJobPrice: 115,
    perMileRate: 4.5,
    availabilityType: "custom" as const,
    services: ["pickup_delivery", "appliance_transport", "furniture_transport", "junk_removal"],
  },
  {
    email: "hannah@truck.local",
    name: "Hannah Brooks",
    fullName: "Hannah Brooks",
    phone: "555-700-8000",
    bio: "Garage sale haul away. Donation drop-offs. Quick turnaround.",
    serviceRadiusMiles: 22,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.6,
    totalJobsCompleted: 44,
    vehicleType: "pickup" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 1900,
    hourlyRate: 70,
    minimumJobPrice: 48,
    perMileRate: 2.3,
    availabilityType: "after_5pm" as const,
    services: ["junk_removal", "pickup_delivery", "yard_waste_haul"],
  },
  {
    email: "pablo@truck.local",
    name: "Pablo Rodriguez",
    fullName: "Pablo Rodriguez",
    phone: "555-800-9000",
    bio: "Snow removal crew. Multiple trucks. Commercial lots and residential.",
    serviceRadiusMiles: 25,
    platformFeePct: 12,
    membershipTier: "premium" as const,
    ratingAvg: 4.8,
    totalJobsCompleted: 234,
    vehicleType: "pickup" as const,
    bedLengthFt: 6.5,
    payloadCapacityLbs: 1800,
    hourlyRate: 92,
    minimumJobPrice: 72,
    perMileRate: 2.8,
    availabilityType: "always" as const,
    services: ["snow_plowing", "salt_spreading", "snow_haul"],
  },
  {
    email: "zoe@truck.local",
    name: "Zoe Anderson",
    fullName: "Zoe Anderson",
    phone: "555-900-1000",
    bio: "Eco-conscious hauling. Recycling and donation priority. Junk removal with a green twist.",
    serviceRadiusMiles: 20,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.7,
    totalJobsCompleted: 38,
    vehicleType: "pickup" as const,
    bedLengthFt: 6.5,
    payloadCapacityLbs: 1500,
    hourlyRate: 72,
    minimumJobPrice: 50,
    perMileRate: 2.4,
    availabilityType: "custom" as const,
    services: ["junk_removal", "yard_waste_haul", "pickup_delivery"],
  },
  {
    email: "greg@truck.local",
    name: "Greg Foster",
    fullName: "Greg Foster",
    phone: "555-101-2020",
    bio: "Handyman with a truck. Small jobs, deliveries, dump runs.",
    serviceRadiusMiles: 18,
    platformFeePct: 15,
    membershipTier: "standard" as const,
    ratingAvg: 4.5,
    totalJobsCompleted: 62,
    vehicleType: "pickup" as const,
    bedLengthFt: 8,
    payloadCapacityLbs: 2200,
    hourlyRate: 75,
    minimumJobPrice: 52,
    perMileRate: 2.5,
    availabilityType: "custom" as const,
    services: ["pickup_delivery", "junk_removal", "small_moves", "yard_waste_haul"],
  },
  {
    email: "lena@truck.local",
    name: "Lena Kowalski",
    fullName: "Lena Kowalski",
    phone: "555-202-3030",
    bio: "Professional mover. Piano specialist. Careful with fragile items.",
    serviceRadiusMiles: 40,
    platformFeePct: 11,
    membershipTier: "premium" as const,
    ratingAvg: 5.0,
    totalJobsCompleted: 145,
    vehicleType: "box_truck" as const,
    bedLengthFt: 22,
    payloadCapacityLbs: 6500,
    hourlyRate: 118,
    minimumJobPrice: 95,
    perMileRate: 3.75,
    availabilityType: "custom" as const,
    services: ["furniture_transport", "appliance_transport", "small_moves", "pickup_delivery"],
  },
  {
    email: "tony@truck.local",
    name: "Tony Russo",
    fullName: "Tony Russo",
    phone: "555-303-4040",
    bio: "Construction debris, demo haul away. Dump runs. Fast and affordable.",
    serviceRadiusMiles: 28,
    platformFeePct: 14,
    membershipTier: "standard" as const,
    ratingAvg: 4.7,
    totalJobsCompleted: 98,
    vehicleType: "dump_truck" as const,
    bedLengthFt: 14,
    payloadCapacityLbs: 11000,
    hourlyRate: 102,
    minimumJobPrice: 82,
    perMileRate: 3.25,
    availabilityType: "always" as const,
    services: ["junk_removal", "yard_waste_haul", "mulch_delivery"],
  },
];

const CUSTOMERS = [
  { email: "jane@customer.local", name: "Jane Doe", address: "123 Main St" },
  { email: "bob@customer.local", name: "Bob Smith", address: "456 Oak Ave" },
  { email: "maria@customer.local", name: "Maria Garcia", address: "789 Pine Rd" },
  { email: "david@customer.local", name: "David Kim", address: "321 Elm St" },
  { email: "rachel@customer.local", name: "Rachel Green", address: "555 Maple Dr" },
  { email: "tom@customer.local", name: "Tom Anderson", address: "777 Cedar Ln" },
  { email: "amy@customer.local", name: "Amy Chen", address: "888 Birch Way" },
  { email: "chris@customer.local", name: "Chris Taylor", address: "999 Spruce Ct" },
];

const SEASONAL_OFFERS = [
  { slug: "winter-plow-2025", name: "Winter Plow Specials", description: "Book driveway plowing for the season. Save 10% on recurring bookings.", promoCode: "PLOW25", discountPct: 10, monthStart: 10, dayStart: 1, monthEnd: 2, dayEnd: 28 },
  { slug: "spring-yard-2025", name: "Spring Yard Hauls", description: "Yard cleanup, mulch delivery, debris removal. Get your yard ready for summer.", promoCode: "YARD25", discountPct: 15, monthStart: 2, dayStart: 1, monthEnd: 5, dayEnd: 30 },
  { slug: "summer-move-2025", name: "Summer Moving Special", description: "Moving season is here. 15% off small moves and furniture transport.", promoCode: "MOVE25", discountPct: 15, monthStart: 5, dayStart: 1, monthEnd: 8, dayEnd: 31 },
  { slug: "fall-cleanup-2025", name: "Fall Leaf & Cleanup", description: "Leaf removal and yard waste hauling. Book before the first frost.", promoCode: "FALL25", discountPct: 12, monthStart: 8, dayStart: 1, monthEnd: 11, dayEnd: 15 },
  { slug: "junk-removal-2025", name: "Junk Removal Blitz", description: "Clear out the garage, basement, or attic. 20% off junk removal this month.", promoCode: "JUNK25", discountPct: 20, monthStart: 0, dayStart: 1, monthEnd: 11, dayEnd: 30 },
];

async function main() {
  const now = new Date();
  const truckOwners: { user: { id: string }; owner: { id: string } }[] = [];
  const customerUsers: { id: string }[] = [];

  // Create truck owners with vehicles, pricing, availability, and services
  for (const to of TRUCK_OWNERS) {
    const user = await prisma.user.upsert({
      where: { email: to.email },
      create: {
        email: to.email,
        name: to.name,
        emailVerified: true,
        phone: to.phone,
        phoneVerified: true,
        role: "truck_owner",
      },
      update: {},
    });

    const owner = await prisma.truckOwner.upsert({
      where: { userId: user.id },
      create: {
        userId: user.id,
        fullName: to.fullName,
        phoneNumber: to.phone,
        serviceRadiusMiles: to.serviceRadiusMiles,
        zipCodes: [],
        bio: to.bio,
        driverLicenseVerified: true,
        insuranceConfirmed: true,
        backgroundCheckConsent: true,
        platformFeePct: to.platformFeePct,
        membershipTier: to.membershipTier,
        isVerified: true,
        totalJobsCompleted: to.totalJobsCompleted,
        ratingAvg: to.ratingAvg,
      },
      update: {},
    });

    const existingVehicle = await prisma.vehicle.findFirst({ where: { ownerId: owner.id } });
    if (!existingVehicle) {
      await prisma.vehicle.create({
        data: {
          ownerId: owner.id,
          vehicleType: to.vehicleType,
          bedLengthFt: to.bedLengthFt,
          payloadCapacityLbs: to.payloadCapacityLbs,
          towingCapable: to.vehicleType === "pickup_trailer" || to.vehicleType === "flatbed",
          towCapacityLbs: to.vehicleType === "pickup_trailer" ? 5000 : to.vehicleType === "flatbed" ? 10000 : null,
          hitchType: to.vehicleType === "pickup" || to.vehicleType === "pickup_trailer" ? "2-inch ball" : null,
          awdOr4wd: to.vehicleType === "pickup" || to.vehicleType === "dump_truck",
          hasRamps: true,
          hasStraps: true,
          hasMovingBlankets: ["small_moves", "furniture_transport"].some((s) => to.services.includes(s)),
          hasPlow: to.services.includes("snow_plowing"),
        },
      });
    }

    await prisma.pricingProfile.upsert({
      where: { ownerId: owner.id },
      create: {
        ownerId: owner.id,
        hourlyRate: to.hourlyRate,
        minimumJobPrice: to.minimumJobPrice,
        perMileRate: to.perMileRate,
        emergencySurchargeEnabled: true,
      },
      update: {},
    });

    const dailyHours = to.availabilityType === "custom" ? DAILY_HOURS : null;
    await prisma.availability.upsert({
      where: { ownerId: owner.id },
      create: {
        ownerId: owner.id,
        availabilityType: to.availabilityType,
        dailyHours,
        seasonalAvailability: ["winter", "spring", "summer", "fall"],
        acceptsSameDayJobs: true,
      },
      update: {},
    });

    for (const st of to.services) {
      const seasonalTag = ["snow_plowing", "salt_spreading", "snow_haul"].includes(st)
        ? "winter"
        : ["mulch_delivery", "yard_waste_haul", "leaf_cleanup_haul"].includes(st)
          ? "spring"
          : "all";
      await prisma.serviceOffering.upsert({
        where: { ownerId_serviceType: { ownerId: owner.id, serviceType: st } },
        create: { ownerId: owner.id, serviceType: st, seasonalTag },
        update: {},
      });
    }

    truckOwners.push({ user: { id: user.id }, owner: { id: owner.id } });
  }

  // Create customers
  for (const c of CUSTOMERS) {
    const user = await prisma.user.upsert({
      where: { email: c.email },
      create: {
        email: c.email,
        name: c.name,
        phone: "555-000-0000",
        role: "customer",
      },
      update: {},
    });
    await prisma.customer.upsert({
      where: { userId: user.id },
      create: { userId: user.id, address: c.address },
      update: {},
    });
    customerUsers.push({ id: user.id });
  }

  // Create sample jobs (customer references User.id)
  const jobTemplates = [
    { serviceType: "junk_removal", pickup: "123 Main St", dropoff: "Recycling Center", amount: 125, ownerIdx: 1 },
    { serviceType: "small_moves", pickup: "456 Oak Ave", dropoff: "789 Pine Rd", amount: 180, ownerIdx: 0 },
    { serviceType: "snow_plowing", pickup: "321 Elm St", dropoff: null, amount: 75, ownerIdx: 2 },
    { serviceType: "mulch_delivery", pickup: "Garden Supply", dropoff: "555 Maple Dr", amount: 95, ownerIdx: 3 },
    { serviceType: "furniture_transport", pickup: "777 Cedar Ln", dropoff: "888 Birch Way", amount: 220, ownerIdx: 5 },
    { serviceType: "pickup_delivery", pickup: "Store", dropoff: "999 Spruce Ct", amount: 65, ownerIdx: 0 },
    { serviceType: "appliance_transport", pickup: "Best Buy", dropoff: "123 Main St", amount: 110, ownerIdx: 4 },
    { serviceType: "yard_waste_haul", pickup: "456 Oak Ave", dropoff: "Landfill", amount: 140, ownerIdx: 6 },
    { serviceType: "junk_removal", pickup: "789 Pine Rd", dropoff: "Junk Yard", amount: 165, ownerIdx: 6 },
    { serviceType: "snow_plowing", pickup: "321 Elm St", dropoff: null, amount: 80, ownerIdx: 2 },
    { serviceType: "small_moves", pickup: "555 Maple Dr", dropoff: "New Apt", amount: 195, ownerIdx: 8 },
    { serviceType: "firewood_delivery", pickup: "Lumber Yard", dropoff: "777 Cedar Ln", amount: 85, ownerIdx: 3 },
    { serviceType: "leaf_cleanup_haul", pickup: "888 Birch Way", dropoff: "Compost", amount: 72, ownerIdx: 9 },
    { serviceType: "pickup_delivery", pickup: "IKEA", dropoff: "999 Spruce Ct", amount: 88, ownerIdx: 7 },
    { serviceType: "furniture_transport", pickup: "123 Main St", dropoff: "456 Oak Ave", amount: 250, ownerIdx: 8 },
    { serviceType: "junk_removal", pickup: "789 Pine Rd", dropoff: "Donation Center", amount: 98, ownerIdx: 0 },
    { serviceType: "salt_spreading", pickup: "321 Elm St", dropoff: null, amount: 55, ownerIdx: 2 },
    { serviceType: "mulch_delivery", pickup: "Nursery", dropoff: "555 Maple Dr", amount: 105, ownerIdx: 9 },
    { serviceType: "appliance_transport", pickup: "Home Depot", dropoff: "777 Cedar Ln", amount: 92, ownerIdx: 1 },
    { serviceType: "small_moves", pickup: "888 Birch Way", dropoff: "Storage Unit", amount: 155, ownerIdx: 4 },
  ];

  for (let i = 0; i < jobTemplates.length; i++) {
    const jt = jobTemplates[i];
    const owner = truckOwners[jt.ownerIdx];
    const customer = customerUsers[i % customerUsers.length];
    const platformFee = Number((jt.amount * 0.15).toFixed(2));
    const scheduledAt = new Date(now);
    scheduledAt.setDate(scheduledAt.getDate() - (i % 14));
    const completedAt = new Date(scheduledAt);
    completedAt.setHours(completedAt.getHours() + 2);

    await prisma.job.upsert({
      where: { id: `seed-job-${i}` },
      create: {
        id: `seed-job-${i}`,
        customerId: customer.id,
        truckOwnerId: owner.owner.id,
        serviceType: jt.serviceType,
        status: "completed",
        pickupAddress: jt.pickup,
        dropoffAddress: jt.dropoff,
        totalAmount: jt.amount,
        platformFee,
        scheduledAt,
        completedAt,
      },
      update: {},
    });
  }

  // Create seasonal offers
  for (const so of SEASONAL_OFFERS) {
    const startDate = new Date(now.getFullYear(), so.monthStart, so.dayStart);
    const endDate = new Date(now.getFullYear() + (so.monthEnd < so.monthStart ? 1 : 0), so.monthEnd, so.dayEnd);
    await prisma.seasonalOffer.upsert({
      where: { slug: so.slug },
      create: {
        slug: so.slug,
        name: so.name,
        description: so.description,
        startDate,
        endDate,
        isActive: true,
        promoCode: so.promoCode,
        discountPct: so.discountPct,
      },
      update: {},
    });
  }

  console.log(
    `Seeded ${TRUCK_OWNERS.length} truck owners, ${CUSTOMERS.length} customers, ${jobTemplates.length} jobs, ${SEASONAL_OFFERS.length} seasonal offers.`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
